language: python
before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
install:
  - conda env create --file ci-environment.yml
  - conda activate ssml
  #   - conda install -c conda-forge coveralls
  - pip install .
script:
  - conda activate ssml
  - flake8
  - pytest --tb=short -m "not gpu" --strict --cov=shadow tests
# after_success:
#   - coveralls
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: iDjVC1lo/3UEJ0wMRv7PnpKezkLXIG45Yq7oLnknCXNF1uQPHe/hfnxxbdJiJ7i3eveohkWdERdtBL+A1PqmHy7e9FVgHJPDImI1Sg3jLu/P6nchd+9bGDKqy+R88kKVLTK/0P5RjeZ7GipNcF2aVPYBU32SaM7IJ40cM4N5w/ehkoBQ0iDRk4w1TckRVetJoUpdpUR0inWP7ivCpuPZeQWagP+3M/g5LpJFQOCSYYaFlzzMNSUBnUFTa/m9aIuQ6AwDxNGOcf6kGQujg6FCzVnM9xDEQ7G91b/NusFdkGt7C7H5Lzf5QRT1k4ib6tR4rnhypxRwlScD7tTft0pF8aYzyPtq4eL+ZzZMcloQUICx7hUat+rovWvCraP6SLlr+OR+IiZ7Mj/dDM4YHAhPj9Aa1IZYFlFpo+vINzLRLVgrLyDPoRAkobGCrENLrtZuVlz/2RcwIkF0hnnq9wY136HdPXKQy+Hw4McmCcE2C/UOtWPzQUHom/GFw84U+cyvvlrSs1aqXFAnoXFAd60se1hp3ZcoUjP7HT4fejV3TkwGbPRTnztp/BUn++NRNWLgfQIaXdYV57V7zVJbNlurGqYe1QCm+6DyK91MuRbIbIhUf81Y0IOpxlnZuMQ/ACWK8JqZcDmVE5gn3AQFJ38V9vCZrsgeXA+IjmbvT7jz7rQ=
  on:
    branch: master
    tags: true
