name: ssml
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - pillow<7 # https://github.com/pytorch/vision/issues/1712#issuecomment-570286349
  - pytest
  - pytest-cov
  - pluggy
  - flake8
  - scikit-learn
  - sphinx=2
  - sphinx_rtd_theme
  - nbsphinx
  - jupyter
  - matplotlib
  - conda-build
