name: ssml
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pytest
  - pytest-cov
  - pluggy
  - flake8
  - scikit-learn
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - jupyter
  - matplotlib
